version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomw1808/laravelproject
    container_name: app
    restart: unless-stopped
    volumes: 
      - ./:/var/www
      - ./blog/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: tomw1808/nginx  
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./blog/config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
