version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomw1808/laravelproject
    container_name: blog
    restart: unless-stopped
    environment:
      # DB_CONNECTION=mysql
      DB_HOST: db
      # DB_PORT=3306
      # DB_DATABASE=laravel
      # DB_USERNAME=root
      DB_PASSWORD: laraVel_passWord
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes: 
      - ./:/var/www
      - ./blog/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: tomw1808/nginx  
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./blog/config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: db
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laraVel_passWord
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis

volumes:
  dbdata:
    driver: local

